import polib


def generate_translation_keys(po_file_path: str, output_file_path: str):
    """
    Generate a Python file with translation keys from a .po file.

    Args:
        po_file_path (str): Path to the .po file.
        output_file_path (str): Path to the output Python file.
    """
    # Load the .po file
    po = polib.pofile(po_file_path)

    # Extract all msgid entries
    keys = [entry.msgid for entry in po if entry.msgid]

    # Generate the Python file content
    with open(output_file_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated translation keys\n")
        f.write("# Do not edit this file manually\n\n")
        f.write("class TranslationKeys:\n")
        for key in keys:
            # Convert msgid to a valid Python constant name
            constant_name = key.upper().replace(" ", "_").replace("-", "_")
            f.write(f"    {constant_name} = \"{key}\"\n")

    print(f"Translation keys have been generated in {output_file_path}")


# Example usage
if __name__ == "__main__":
    # Path to the .po file
    po_file = "c:/projects/tandorost-platform/locales/en/LC_MESSAGES/messages.po"

    # Path to the output Python file
    output_file = "c:/projects/tandorost-platform/utility/translation_keys.py"

    # Generate the translation keys
    generate_translation_keys(po_file, output_file)