# Auto-generated translation keys
# Do not edit this file manually

class TranslationKeys:
    USERNAME_IN_USE = "username_in_use"
    WELCOME_MESSAGE = "welcome_message"
    INVALID_CREDENTIALS = "invalid_credentials"
    INCORRECT_CREDENTIALS = "incorrect_credentials"
    REMOTE_SERVICE_UNAVAILABLE = "remote_service_unavailable"
    USER_REGISTERED = "user_registered"
    RATE_LIMIT_REACH = "rate_limit_reach"
    USERNAME_NOT_REGISTERED_YET = "username_not_registered_yet"
    INVALID_VERIFICATION_CODE = "invalid_verification_code"
    USERNAME_IS_INACTIVE = "username_is_inactive"
    INVALID_PASSWORD = "invalid_password"
    PASSWORD_RESTORED = "password_restored"
    INVALID_TOKEN = "invalid_token"
    USER_NOT_FOUND = "user_not_found"
    OBJECT_NOT_FOUND = "object_not_found"
    VERIFICATION_CODE_SEND = "verification_code_send"
