# Auto-generated translation keys
# Do not edit this file manually

class TranslationKeys:
    USERNAME_IN_USE = "username_in_use"
    WELCOME_MESSAGE = "welcome_message"
    INVALID_CREDENTIALS = "invalid_credentials"
    INCORRECT_CREDENTIALS = "incorrect_credentials"
